spring.application.name=gestiondespachos
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=8080

# Ruta local o volumen montado para archivos generados.
app.efs.mount-path=${EFS_MOUNT_PATH:./efs-temporal}

# Configuracion AWS/S3.
cloud.aws.region.static=${AWS_REGION:us-east-1}
cloud.aws.stack.auto=false
app.s3.bucket-name=${AWS_S3_BUCKET_NAME:}

# Azure AD B2C / JWT.
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_B2C_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_B2C_JWK_SET_URI}
spring.security.oauth2.resourceserver.jwt.audiences[0]=${AZURE_B2C_AUDIENCE}