spring.application.name=gestiondespachos
spring.profiles.active=dev
server.port=8080

# Ruta local para simular EFS en desarrollo.
app.efs.mount-path=${EFS_MOUNT_PATH:./efs-temporal}

# Configuración AWS/S3.
cloud.aws.region.static=${AWS_REGION:us-east-1}
cloud.aws.stack.auto=false
app.s3.bucket-name=${AWS_S3_BUCKET_NAME:}